name: QueryArrow-db-remote
version: '0.2'
author: Hao Xu
license: BSD3
ghc-options:
- -Wall
- -fPIC
dependencies:
- base >=4
- containers
- mtl
- aeson
- scientific
- transformers
- semigroups
- semigroupoids
- unordered-containers
- resourcet
- network
- hslogger
- lifted-base
- constraints
- data-msgpack
- binary
- bytestring
- heterogeneous-list
- QueryArrow-common
- QueryArrow-rpc-common
- template-haskell
library:
  source-dirs: src
  exposed-modules:
  - QueryArrow.Remote.Channel
  - QueryArrow.Remote.Definitions
  - QueryArrow.Remote.Serialization
  - QueryArrow.Remote.NoTranslation.Definitions
  - QueryArrow.Remote.NoTranslation.Serialization
  - QueryArrow.Remote.NoTranslation.Server
  - QueryArrow.Remote.NoTranslation.Client
  - QueryArrow.Remote.NoTranslation.TCP.TCP
