name: QueryArrow-rpc-filesystem
version: '0.2'
author: Hao Xu
license: BSD3
ghc-options:
- -Wall
- -fPIC
- -threaded
dependencies:
- base >=4
- mtl
- transformers
- containers
- aeson
- resourcet
- time
- hslogger
- network
- directory
- optparse-applicative
- QueryArrow-plugins
- QueryArrow-rpc-common
- QueryArrow-common
- QueryArrow-rpc-http
# - QueryArrow-db-filesystem
- QueryArrow-ffi-service
- log-adapter
library:
  source-dirs: src
  exposed-modules:
  - QueryArrow.RPC.Socket.Common
  - QueryArrow.RPC.Socket.TCP
  - QueryArrow.RPC.Socket.UDS
