name: QueryArrow-db-cypher
version: '0.2'
author: Hao Xu
license: BSD3
dependencies:
- base >=4
- containers
- transformers
- bytestring
- hasbolt
- unordered-containers
- convertible
- text >=1.2.1.1
- scientific
- aeson
- lattices
- conduit
- data-default
- QueryArrow-rpc-common
- hslogger
- namespace >=0.1.2.2
- heterogeneous-list
- semibounded-lattices
- QueryArrow-common
- QueryArrow-sql-common
- QueryArrow-db-sql-common
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fPIC
  exposed-modules:
  - QueryArrow.DB.Cypher.Neo4j
  - QueryArrow.DB.Cypher.Neo4jConnection
  - QueryArrow.DB.Cypher.BuiltIn
  - QueryArrow.DB.Cypher.Cypher
  - QueryArrow.DB.Cypher.Mapping
  - QueryArrow.DB.Cypher.SQLToCypher
  dependencies: []
tests:
  Test:
    main: Test.hs
    source-dirs:
    - src
    - test
    dependencies:
    - mtl
    - semigroups
    - parsec
    - semigroupoids
    - QuickCheck
    - hspec
    - array
    - process
    - conduit-combinators
    - conduit
    - resourcet
    - async
    - time
    - exceptions
    - utf8-string
    - directory
    - template-haskell
