name: QueryArrow-db-cache
version: '0.2'
author: Hao Xu
license: BSD3
ghc-options:
- -Wall
- -fPIC
dependencies:
- base >=4
- containers
- mtl
- transformers
- semigroups
- parsec
- semigroupoids
- aeson
- bytestring
- unordered-containers
- convertible
- text >=1.2.1.1
- scientific
- array
- conduit-combinators
- conduit
- resourcet
- async
- time
- hslogger
- exceptions
- utf8-string
- regex-tdfa
- lifted-async
- namespace >=0.1.2.2
- lattices
- semibounded-lattices
- conduit-extra
- cpphs
- monad-logger
- fast-logger
- constraints
- either
- lrucache
- heterogeneous-list
- log-adapter
- QueryArrow-common
library:
  source-dirs: src
  exposed-modules:
  - QueryArrow.Cache
