name: QueryArrow-sql
version: '0.2'
author: Hao Xu
license: BSD3
ghc-options:
- -Wall
- -fPIC
dependencies:
- base >=4
- containers
- mtl
- transformers
- semigroups
- parsec
- semigroupoids
- unordered-containers
- text >=1.2.1.1
- hslogger
- namespace >=0.1.2.2
- either
- lattices
- QueryArrow-common
- QueryArrow-db-sql-common
library:
  source-dirs: src
  exposed-modules:
  - QueryArrow.SQL.Translate
  - QueryArrow.SQL.Parser
