name: QueryArrow-db-elastic
version: '0.2'
author: Hao Xu
license: BSD3
ghc-options:
- -Wall
- -fPIC
dependencies:
- base >=4
- aeson
- containers
- mtl
- transformers
- semigroups
- parsec
- semigroupoids
- HDBC-sqlite3
- HDBC-postgresql
- HDBC
- aeson
- bytestring
- unordered-containers
- convertible
- text >=1.2.1.1
- scientific
- array
- temporary
- process
- conduit-combinators
- conduit
- http-conduit
- resourcet
- async
- time
- hslogger
- exceptions
- utf8-string
- regex-tdfa
- monad-control
- lifted-async
- namespace >=0.1.2.2
- lattices
- semibounded-lattices
- network
- conduit-extra
- monad-logger
- fast-logger
- heterogeneous-list
- constraints
- data-msgpack
- QueryArrow-common
- template-haskell
library:
  source-dirs: src
  exposed-modules:
  - QueryArrow.DB.ElasticSearch.ElasticSearch
  - QueryArrow.DB.ElasticSearch.Connection
  - QueryArrow.DB.ElasticSearch.ESQL
  - QueryArrow.DB.ElasticSearch.Query
  - QueryArrow.DB.ElasticSearch.QueryResult
  - QueryArrow.DB.ElasticSearch.QueryResultHits
  - QueryArrow.DB.ElasticSearch.ICAT
  - QueryArrow.DB.ElasticSearch.Record
  - QueryArrow.DB.ElasticSearch.HTTP.ElasticSearchUtils
