name: QueryArrow-ffi-c-unixdomainsocket
version: '0.2'
author: Hao Xu
license: BSD3
ghc-options:
- -Wall
- -fPIC
- -shared
- -dynamic
dependencies:
- base >=4
- hslogger
- QueryArrow-ffi-service
- QueryArrow-ffi-service-unixdomainsocket
- QueryArrow-ffi-service-handle-common
library:
  source-dirs: src
  exposed-modules:
  - QueryArrow.FFI.C.UnixDomainSocket
