name: QueryArrow-gen
version: '0.2'
author: Hao Xu
license: BSD3
build-type: Custom
library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - base >=4
    - QueryArrow-gen-tool
  exposed-modules:
    - QueryArrow.Gen
