template_translation:
  rewriting_file_path : ../QueryArrow-gen/rewriting-plugin-gen.rules
  include_file_path:
    - ../QueryArrow-gen
  trans_db_plugin:
    qap_name: ""
    catalog_database_type: ""
template_db:
  db_port: 5432
  db_name: ICAT
  db_password: testpassword
  db_host: localhost
  db_username: irods
  db_predicates: ../QueryArrow-gen/gen/ICATGen
  db_namespace: ICAT
  db_sql_mapping: ../QueryArrow-gen/gen/SQL/ICATGen
