name: QueryArrow-rpc-common
version: '0.2'
author: Hao Xu
license: BSD3
ghc-options:
- -Wall
- -fPIC
dependencies:
- base >=4
- transformers
- aeson
- containers
- bytestring
- binary
- mtl
- resourcet
- either
- namespace
- hslogger
- parsec
- text
- base64-bytestring
- unix
- data-msgpack
- log-adapter
- yaml
- free
- conduit
- QueryArrow-common
library:
  source-dirs: src
  exposed-modules:
  - QueryArrow.Serialization
  - QueryArrow.RPC.Message
  - QueryArrow.RPC.DB
  - QueryArrow.RPC.Config
  - QueryArrow.RPC.Service
