name: QueryArrow-ffi-service
version: '0.2'
author: Hao Xu
license: BSD3
ghc-options:
- -Wall
- -fPIC
dependencies:
- base >=4
- containers
- mtl
- transformers
- semigroups
- semigroupoids
- bytestring
- unordered-containers
- convertible
- text >=1.2.1.1
- scientific
- array
- process
- time
- hslogger
- exceptions
- utf8-string
- monad-control
- namespace >=0.1.2.2
- monad-logger
- fast-logger
- constraints
- either
- HDBC
- QueryArrow-common
- QueryArrow-db-sql-hdbc-common
- QueryArrow-rpc-common
- template-haskell
library:
  source-dirs: src
  exposed-modules:
  - QueryArrow.FFI.Auxiliary
  - QueryArrow.FFI.Service
