name: QueryArrow-db-sql-hdbc-common
version: '0.2'
author: Hao Xu
license: BSD3
ghc-options:
- -Wall
- -fPIC
dependencies:
- base >=4
- aeson
- containers
- mtl
- transformers
- HDBC
- convertible
- text >=1.2.1.1
- hslogger
- namespace >=0.1.2.2
- lattices
- semibounded-lattices
- QueryArrow-db-sql-common
- QueryArrow-common
library:
  source-dirs: src
  exposed-modules:
  - QueryArrow.DB.SQL.HDBC
