name: QueryArrow-plugins
version: '0.2'
author: Hao Xu
license: BSD3
ghc-options:
- -Wall
- -fPIC
dependencies:
- base >=4
- hslogger
- mtl
- containers
- namespace >=0.1.2.2
- QueryArrow-common
- QueryArrow-db-inmemory
- QueryArrow-db-sql-hdbc-common
- QueryArrow-db-sql-hdbc-cockroachdb
- QueryArrow-db-sql-hdbc-postgresql
- QueryArrow-db-sql-hdbc-sqlite3
- QueryArrow-db-sql-libpq-postgresql
- QueryArrow-db-cypher
- QueryArrow-db-elastic
- QueryArrow-db-include
- QueryArrow-db-trans
- QueryArrow-db-sum
- QueryArrow-db-cache
- heterogeneous-list
library:
  source-dirs: src
  exposed-modules:
  - QueryArrow.DBMap
