name: QueryArrow-common
version: '0.2'
author: Hao Xu
license: BSD3
dependencies:
- base >=4
- containers
- mtl
- transformers
- semigroups
- parsec
- semigroupoids
- aeson
- bytestring
- unordered-containers
- convertible
- text >=1.2.1.1
- scientific
- array
- conduit-combinators
- conduit
- resourcet
- async
- time
- exceptions
- utf8-string
- lattices
- hslogger
- regex-tdfa
- lifted-async
- namespace >=0.1.2.2
- semibounded-lattices
- conduit-extra
- monad-logger
- fast-logger
- constraints
- either
- yaml
- filepath
- binary
- base64-bytestring
- comonad
- free
- deriving-compat
- heterogeneous-list
- log-adapter
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fPIC
  exposed-modules:
  - QueryArrow.Syntax.Term
  - QueryArrow.Semantics.TypeChecker
  - QueryArrow.Semantics.Domain
  - QueryArrow.Syntax.Utils
  - QueryArrow.Syntax.Serialize
  - QueryArrow.Syntax.Type
  - QueryArrow.Semantics.Compute
  - QueryArrow.Semantics.Value
  - QueryArrow.Serialization
  - QueryArrow.DB.DB
  - QueryArrow.DB.NoTranslation
  - QueryArrow.DB.GenericDatabase
  - QueryArrow.DB.NoConnection
  - QueryArrow.DB.ParametrizedStatement
  - QueryArrow.DB.ResultStream
  - QueryArrow.DB.AbstractDatabaseList
  - QueryArrow.Mapping
  - QueryArrow.BuiltIn
  - QueryArrow.QueryPlan
  - QueryArrow.Logging
  - QueryArrow.Parser
  - QueryArrow.Config
  - QueryArrow.ListUtils
  - QueryArrow.Utils
  - QueryArrow.Plugin
  dependencies: []
tests:
  Test:
    main: Test.hs
    source-dirs:
    - src
    - test
    dependencies:
    - QuickCheck
    - hspec
    - temporary
    - process
    - http-conduit
    - cereal
    - directory
    - template-haskell
