name: QueryArrow-ffi-c-genquery
version: '0.2'
author: Hao Xu
license: BSD3
dependencies:
- base >=4
- containers
- mtl
- transformers
- semigroups
- parsec
- semigroupoids
- aeson
- bytestring
- unordered-containers
- convertible
- text >=1.2.1.1
- scientific
- array
- temporary
- process
- resourcet
- async
- time
- hslogger
- exceptions
- utf8-string
- regex-tdfa
- monad-control
- lifted-async
- namespace >=0.1.2.2
- lattices
- semibounded-lattices
- monad-logger
- fast-logger
- constraints
- either
- QueryArrow-common
- QueryArrow-ffi-service
- QueryArrow-ffi-genquery
- template-haskell
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fPIC
  - -shared
  - -dynamic
  exposed-modules:
  - QueryArrow.FFI.C.GenQuery
executables:
  GenQueryTrans:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
