name: QueryArrow-rpc-http
version: '0.2'
author: Hao Xu
license: BSD3
ghc-options:
- -Wall
- -fPIC
dependencies:
- base >=4
- containers
- mtl
- transformers
- semigroups
- parsec
- semigroupoids
- HDBC-sqlite3
- HDBC-postgresql
- HDBC
- aeson
- bytestring
- unordered-containers
- convertible
- text >=1.2.1.1
- scientific
- array
- temporary
- process
- conduit-combinators
- conduit
- resourcet
- async
- time
- hslogger
- exceptions
- utf8-string
- regex-tdfa
- monad-control
- lifted-async
- namespace >=0.1.2.2
- lattices
- semibounded-lattices
- network
- conduit-extra
- monad-logger
- fast-logger
- optparse-applicative
- constraints
- yesod
- either
- QueryArrow-rpc-common
- QueryArrow-common
- QueryArrow-plugins
- template-haskell
library:
  source-dirs: src
  exposed-modules:
  - QueryArrow.RPC.Service.HTTP
