name: log-adapter
version: '0.2'
author: Hao Xu
license: BSD3
ghc-options:
- -Wall
- -fPIC
dependencies:
- base >=4
- containers
- mtl
- transformers
- bytestring
- unordered-containers
- convertible
- text >=1.2.1.1
- hslogger
- monad-logger
- fast-logger
library:
  source-dirs: src
  exposed-modules:
  - QueryArrow.Control.Monad.Logger.HSLogger
