name: QueryArrow-ffi-c
version: '0.2'
author: Hao Xu
license: BSD3
ghc-options:
- -Wall
- -fPIC
- -shared
- -dynamic
dependencies:
- base >=4
- containers
- mtl
- transformers
- semigroups
- parsec
- semigroupoids
- aeson
- bytestring
- unordered-containers
- convertible
- text >=1.2.1.1
- scientific
- array
- temporary
- process
- resourcet
- async
- time
- hslogger
- exceptions
- utf8-string
- regex-tdfa
- monad-control
- lifted-async
- namespace >=0.1.2.2
- lattices
- semibounded-lattices
- monad-logger
- fast-logger
- constraints
- either
- QueryArrow-common
- QueryArrow-db-trans
- QueryArrow-ffi-service
- QueryArrow-db-sql-common
- QueryArrow-db-sql-hdbc-common
- QueryArrow-gen
- QueryArrow-db-sql-hdbc-postgresql
- template-haskell
library:
  source-dirs: src
  exposed-modules:
  - QueryArrow.FFI.C.Plugin
  - QueryArrow.FFI.C.Template
  - QueryArrow.FFI.C.PluginGen
